### ISSUE TITLE
Your developer forum is down and the developer docs for generating an API key are wrong.

### ISSUE THREAD

**Issue by gpwclark** [VeeqoAPI/api-docs#16]
https://developer-forum.veeqo.com/

isn't working

and your instructions for generating an API key are wrong: https://developer.veeqo.com/docs#/introduction/authentication/generating-your-api-keys

The employees page has no mention of refreshing keys anywhere and is now the users page.

**Comment by DimuDesigns** [comment]
They deprecated the developer forum on July 14th 2024. But there are still dead links to the forum on the main site. The forum was a valuable resource, but it looks like Amazon is planning on revamping the API to better integrate with its AWS ecosystem (at least that's my guess).
 
Veeqo's API has always been somewhat wonky even before Amazon's acquisition. Now that its under new stewardship we can only hope that these bugs are addressed and the service improves. But I don't expect to see any changes anytime soon.

**Comment by gpwclark** [comment]
thanks for your reply!

**Comment by DimuDesigns** [comment]
The developer forum is back up again. Looks like Amazon was just migrating away from the previous forum platform.
